# Generated by Django 4.1.7 on 2023-04-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_student_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_t', models.CharField(max_length=100)),
                ('section_t', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('date_t', models.DateTimeField(auto_now_add=True)),
                ('start_t', models.CharField(max_length=100)),
                ('end_t', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_id',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
