# Generated by Django 4.1.7 on 2023-04-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_timetable_remove_student_course_id_delete_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='date_t',
        ),
    ]
