# Generated by Django 4.1.7 on 2023-04-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_rename_end_t_timetable_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='class_name',
            field=models.IntegerField(max_length=100),
        ),
    ]
